//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: polo.proto

package com.google.polo.wire.protobuf;

@kotlin.jvm.JvmName("-initializeoptions")
inline fun options(block: com.google.polo.wire.protobuf.OptionsKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.Options =
  com.google.polo.wire.protobuf.OptionsKt.Dsl._create(com.google.polo.wire.protobuf.PoloProto.Options.newBuilder()).apply { block() }._build()
object OptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.google.polo.wire.protobuf.PoloProto.Options.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.polo.wire.protobuf.PoloProto.Options.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.polo.wire.protobuf.PoloProto.Options = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class InputEncodingsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
     val inputEncodings: com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInputEncodingsList()
      )
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     * @param value The inputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.add(value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      _builder.addInputEncodings(value)
    }
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     * @param value The inputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInputEncodings")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.plusAssign(value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      add(value)
    }
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     * @param values The inputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.addAll(values: kotlin.collections.Iterable<com.google.polo.wire.protobuf.PoloProto.Options.Encoding>) {
      _builder.addAllInputEncodings(values)
    }
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     * @param values The inputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInputEncodings")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.polo.wire.protobuf.PoloProto.Options.Encoding>) {
      addAll(values)
    }
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     * @param index The index to set the value at.
     * @param value The inputEncodings to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInputEncodings")
    operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.set(index: kotlin.Int, value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      _builder.setInputEncodings(index, value)
    }
    /**
     * <pre>
     * List of encodings this endpoint accepts when serving as an input device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, InputEncodingsProxy>.clear() {
      _builder.clearInputEncodings()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class OutputEncodingsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
     val outputEncodings: com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOutputEncodingsList()
      )
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     * @param value The outputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOutputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.add(value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      _builder.addOutputEncodings(value)
    }
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     * @param value The outputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOutputEncodings")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.plusAssign(value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      add(value)
    }
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     * @param values The outputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOutputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.addAll(values: kotlin.collections.Iterable<com.google.polo.wire.protobuf.PoloProto.Options.Encoding>) {
      _builder.addAllOutputEncodings(values)
    }
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     * @param values The outputEncodings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOutputEncodings")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.polo.wire.protobuf.PoloProto.Options.Encoding>) {
      addAll(values)
    }
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     * @param index The index to set the value at.
     * @param value The outputEncodings to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOutputEncodings")
    operator fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.set(index: kotlin.Int, value: com.google.polo.wire.protobuf.PoloProto.Options.Encoding) {
      _builder.setOutputEncodings(index, value)
    }
    /**
     * <pre>
     * List of encodings this endpoint can generate as an output device.
     * </pre>
     *
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOutputEncodings")
    fun com.google.protobuf.kotlin.DslList<com.google.polo.wire.protobuf.PoloProto.Options.Encoding, OutputEncodingsProxy>.clear() {
      _builder.clearOutputEncodings()
    }


    /**
     * <pre>
     * Preferred role, if any.
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     */
     var preferredRole: com.google.polo.wire.protobuf.PoloProto.Options.RoleType
      @JvmName("getPreferredRole")
      get() = _builder.getPreferredRole()
      @JvmName("setPreferredRole")
      set(value) {
        _builder.setPreferredRole(value)
      }
    /**
     * <pre>
     * Preferred role, if any.
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     */
    fun clearPreferredRole() {
      _builder.clearPreferredRole()
    }
    /**
     * <pre>
     * Preferred role, if any.
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     * @return Whether the preferredRole field is set.
     */
    fun hasPreferredRole(): kotlin.Boolean {
      return _builder.hasPreferredRole()
    }
  }
  @kotlin.jvm.JvmName("-initializeencoding")
  inline fun encoding(block: com.google.polo.wire.protobuf.OptionsKt.EncodingKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.Options.Encoding =
    com.google.polo.wire.protobuf.OptionsKt.EncodingKt.Dsl._create(com.google.polo.wire.protobuf.PoloProto.Options.Encoding.newBuilder()).apply { block() }._build()
  object EncodingKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
      private val _builder: com.google.polo.wire.protobuf.PoloProto.Options.Encoding.Builder
    ) {
      companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.polo.wire.protobuf.PoloProto.Options.Encoding.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.polo.wire.protobuf.PoloProto.Options.Encoding = _builder.build()

      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       */
       var type: com.google.polo.wire.protobuf.PoloProto.Options.Encoding.EncodingType
        @JvmName("getType")
        get() = _builder.getType()
        @JvmName("setType")
        set(value) {
          _builder.setType(value)
        }
      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       */
      fun clearType() {
        _builder.clearType()
      }
      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       * @return Whether the type field is set.
       */
      fun hasType(): kotlin.Boolean {
        return _builder.hasType()
      }

      /**
       * <code>required uint32 symbol_length = 2;</code>
       */
      var symbolLength: kotlin.Int
        @JvmName("getSymbolLength")
        get() = _builder.getSymbolLength()
        @JvmName("setSymbolLength")
        set(value) {
          _builder.setSymbolLength(value)
        }
      /**
       * <code>required uint32 symbol_length = 2;</code>
       */
      fun clearSymbolLength() {
        _builder.clearSymbolLength()
      }
      /**
       * <code>required uint32 symbol_length = 2;</code>
       * @return Whether the symbolLength field is set.
       */
      fun hasSymbolLength(): kotlin.Boolean {
        return _builder.hasSymbolLength()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.polo.wire.protobuf.PoloProto.Options.copy(block: com.google.polo.wire.protobuf.OptionsKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.Options =
  com.google.polo.wire.protobuf.OptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
inline fun com.google.polo.wire.protobuf.PoloProto.Options.Encoding.copy(block: com.google.polo.wire.protobuf.OptionsKt.EncodingKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.Options.Encoding =
  com.google.polo.wire.protobuf.OptionsKt.EncodingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

