//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: polo.proto

package com.google.polo.wire.protobuf;

@kotlin.jvm.JvmName("-initializeouterMessage")
inline fun outerMessage(block: com.google.polo.wire.protobuf.OuterMessageKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.OuterMessage =
  com.google.polo.wire.protobuf.OuterMessageKt.Dsl._create(com.google.polo.wire.protobuf.PoloProto.OuterMessage.newBuilder()).apply { block() }._build()
object OuterMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.google.polo.wire.protobuf.PoloProto.OuterMessage.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.polo.wire.protobuf.PoloProto.OuterMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.polo.wire.protobuf.PoloProto.OuterMessage = _builder.build()

    /**
     * <code>required uint32 protocol_version = 1 [default = 1];</code>
     */
    var protocolVersion: kotlin.Int
      @JvmName("getProtocolVersion")
      get() = _builder.getProtocolVersion()
      @JvmName("setProtocolVersion")
      set(value) {
        _builder.setProtocolVersion(value)
      }
    /**
     * <code>required uint32 protocol_version = 1 [default = 1];</code>
     */
    fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }
    /**
     * <code>required uint32 protocol_version = 1 [default = 1];</code>
     * @return Whether the protocolVersion field is set.
     */
    fun hasProtocolVersion(): kotlin.Boolean {
      return _builder.hasProtocolVersion()
    }

    /**
     * <pre>
     * Protocol status. Any status other than STATUS_OK implies a fault.
     * </pre>
     *
     * <code>required .polo.wire.protobuf.OuterMessage.Status status = 2;</code>
     */
     var status: com.google.polo.wire.protobuf.PoloProto.OuterMessage.Status
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <pre>
     * Protocol status. Any status other than STATUS_OK implies a fault.
     * </pre>
     *
     * <code>required .polo.wire.protobuf.OuterMessage.Status status = 2;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * <pre>
     * Protocol status. Any status other than STATUS_OK implies a fault.
     * </pre>
     *
     * <code>required .polo.wire.protobuf.OuterMessage.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * <pre>
     * Initialization phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.PairingRequest pairing_request = 10;</code>
     */
    var pairingRequest: com.google.polo.wire.protobuf.PoloProto.PairingRequest
      @JvmName("getPairingRequest")
      get() = _builder.getPairingRequest()
      @JvmName("setPairingRequest")
      set(value) {
        _builder.setPairingRequest(value)
      }
    /**
     * <pre>
     * Initialization phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.PairingRequest pairing_request = 10;</code>
     */
    fun clearPairingRequest() {
      _builder.clearPairingRequest()
    }
    /**
     * <pre>
     * Initialization phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.PairingRequest pairing_request = 10;</code>
     * @return Whether the pairingRequest field is set.
     */
    fun hasPairingRequest(): kotlin.Boolean {
      return _builder.hasPairingRequest()
    }
    val OuterMessageKt.Dsl.pairingRequestOrNull: com.google.polo.wire.protobuf.PoloProto.PairingRequest?
      get() = _builder.pairingRequestOrNull

    /**
     * <code>optional .polo.wire.protobuf.PairingRequestAck pairing_request_ack = 11;</code>
     */
    var pairingRequestAck: com.google.polo.wire.protobuf.PoloProto.PairingRequestAck
      @JvmName("getPairingRequestAck")
      get() = _builder.getPairingRequestAck()
      @JvmName("setPairingRequestAck")
      set(value) {
        _builder.setPairingRequestAck(value)
      }
    /**
     * <code>optional .polo.wire.protobuf.PairingRequestAck pairing_request_ack = 11;</code>
     */
    fun clearPairingRequestAck() {
      _builder.clearPairingRequestAck()
    }
    /**
     * <code>optional .polo.wire.protobuf.PairingRequestAck pairing_request_ack = 11;</code>
     * @return Whether the pairingRequestAck field is set.
     */
    fun hasPairingRequestAck(): kotlin.Boolean {
      return _builder.hasPairingRequestAck()
    }
    val OuterMessageKt.Dsl.pairingRequestAckOrNull: com.google.polo.wire.protobuf.PoloProto.PairingRequestAck?
      get() = _builder.pairingRequestAckOrNull

    /**
     * <pre>
     * Configuration phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options options = 20;</code>
     */
    var options: com.google.polo.wire.protobuf.PoloProto.Options
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * <pre>
     * Configuration phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options options = 20;</code>
     */
    fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * <pre>
     * Configuration phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Options options = 20;</code>
     * @return Whether the options field is set.
     */
    fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
    val OuterMessageKt.Dsl.optionsOrNull: com.google.polo.wire.protobuf.PoloProto.Options?
      get() = _builder.optionsOrNull

    /**
     * <code>optional .polo.wire.protobuf.Configuration configuration = 30;</code>
     */
    var configuration: com.google.polo.wire.protobuf.PoloProto.Configuration
      @JvmName("getConfiguration")
      get() = _builder.getConfiguration()
      @JvmName("setConfiguration")
      set(value) {
        _builder.setConfiguration(value)
      }
    /**
     * <code>optional .polo.wire.protobuf.Configuration configuration = 30;</code>
     */
    fun clearConfiguration() {
      _builder.clearConfiguration()
    }
    /**
     * <code>optional .polo.wire.protobuf.Configuration configuration = 30;</code>
     * @return Whether the configuration field is set.
     */
    fun hasConfiguration(): kotlin.Boolean {
      return _builder.hasConfiguration()
    }
    val OuterMessageKt.Dsl.configurationOrNull: com.google.polo.wire.protobuf.PoloProto.Configuration?
      get() = _builder.configurationOrNull

    /**
     * <code>optional .polo.wire.protobuf.ConfigurationAck configuration_ack = 31;</code>
     */
    var configurationAck: com.google.polo.wire.protobuf.PoloProto.ConfigurationAck
      @JvmName("getConfigurationAck")
      get() = _builder.getConfigurationAck()
      @JvmName("setConfigurationAck")
      set(value) {
        _builder.setConfigurationAck(value)
      }
    /**
     * <code>optional .polo.wire.protobuf.ConfigurationAck configuration_ack = 31;</code>
     */
    fun clearConfigurationAck() {
      _builder.clearConfigurationAck()
    }
    /**
     * <code>optional .polo.wire.protobuf.ConfigurationAck configuration_ack = 31;</code>
     * @return Whether the configurationAck field is set.
     */
    fun hasConfigurationAck(): kotlin.Boolean {
      return _builder.hasConfigurationAck()
    }
    val OuterMessageKt.Dsl.configurationAckOrNull: com.google.polo.wire.protobuf.PoloProto.ConfigurationAck?
      get() = _builder.configurationAckOrNull

    /**
     * <pre>
     * Pairing phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Secret secret = 40;</code>
     */
    var secret: com.google.polo.wire.protobuf.PoloProto.Secret
      @JvmName("getSecret")
      get() = _builder.getSecret()
      @JvmName("setSecret")
      set(value) {
        _builder.setSecret(value)
      }
    /**
     * <pre>
     * Pairing phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Secret secret = 40;</code>
     */
    fun clearSecret() {
      _builder.clearSecret()
    }
    /**
     * <pre>
     * Pairing phase
     * </pre>
     *
     * <code>optional .polo.wire.protobuf.Secret secret = 40;</code>
     * @return Whether the secret field is set.
     */
    fun hasSecret(): kotlin.Boolean {
      return _builder.hasSecret()
    }
    val OuterMessageKt.Dsl.secretOrNull: com.google.polo.wire.protobuf.PoloProto.Secret?
      get() = _builder.secretOrNull

    /**
     * <code>optional .polo.wire.protobuf.SecretAck secret_ack = 41;</code>
     */
    var secretAck: com.google.polo.wire.protobuf.PoloProto.SecretAck
      @JvmName("getSecretAck")
      get() = _builder.getSecretAck()
      @JvmName("setSecretAck")
      set(value) {
        _builder.setSecretAck(value)
      }
    /**
     * <code>optional .polo.wire.protobuf.SecretAck secret_ack = 41;</code>
     */
    fun clearSecretAck() {
      _builder.clearSecretAck()
    }
    /**
     * <code>optional .polo.wire.protobuf.SecretAck secret_ack = 41;</code>
     * @return Whether the secretAck field is set.
     */
    fun hasSecretAck(): kotlin.Boolean {
      return _builder.hasSecretAck()
    }
    val OuterMessageKt.Dsl.secretAckOrNull: com.google.polo.wire.protobuf.PoloProto.SecretAck?
      get() = _builder.secretAckOrNull
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.polo.wire.protobuf.PoloProto.OuterMessage.copy(block: com.google.polo.wire.protobuf.OuterMessageKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.OuterMessage =
  com.google.polo.wire.protobuf.OuterMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.pairingRequestOrNull: com.google.polo.wire.protobuf.PoloProto.PairingRequest?
  get() = if (hasPairingRequest()) getPairingRequest() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.pairingRequestAckOrNull: com.google.polo.wire.protobuf.PoloProto.PairingRequestAck?
  get() = if (hasPairingRequestAck()) getPairingRequestAck() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.optionsOrNull: com.google.polo.wire.protobuf.PoloProto.Options?
  get() = if (hasOptions()) getOptions() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.configurationOrNull: com.google.polo.wire.protobuf.PoloProto.Configuration?
  get() = if (hasConfiguration()) getConfiguration() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.configurationAckOrNull: com.google.polo.wire.protobuf.PoloProto.ConfigurationAck?
  get() = if (hasConfigurationAck()) getConfigurationAck() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.secretOrNull: com.google.polo.wire.protobuf.PoloProto.Secret?
  get() = if (hasSecret()) getSecret() else null

val com.google.polo.wire.protobuf.PoloProto.OuterMessageOrBuilder.secretAckOrNull: com.google.polo.wire.protobuf.PoloProto.SecretAck?
  get() = if (hasSecretAck()) getSecretAck() else null

