//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: polo.proto

package com.google.polo.wire.protobuf;

@kotlin.jvm.JvmName("-initializesecretAck")
inline fun secretAck(block: com.google.polo.wire.protobuf.SecretAckKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.SecretAck =
  com.google.polo.wire.protobuf.SecretAckKt.Dsl._create(com.google.polo.wire.protobuf.PoloProto.SecretAck.newBuilder()).apply { block() }._build()
object SecretAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.google.polo.wire.protobuf.PoloProto.SecretAck.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.polo.wire.protobuf.PoloProto.SecretAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.polo.wire.protobuf.PoloProto.SecretAck = _builder.build()

    /**
     * <code>required bytes secret = 1;</code>
     */
    var secret: com.google.protobuf.ByteString
      @JvmName("getSecret")
      get() = _builder.getSecret()
      @JvmName("setSecret")
      set(value) {
        _builder.setSecret(value)
      }
    /**
     * <code>required bytes secret = 1;</code>
     */
    fun clearSecret() {
      _builder.clearSecret()
    }
    /**
     * <code>required bytes secret = 1;</code>
     * @return Whether the secret field is set.
     */
    fun hasSecret(): kotlin.Boolean {
      return _builder.hasSecret()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.polo.wire.protobuf.PoloProto.SecretAck.copy(block: com.google.polo.wire.protobuf.SecretAckKt.Dsl.() -> kotlin.Unit): com.google.polo.wire.protobuf.PoloProto.SecretAck =
  com.google.polo.wire.protobuf.SecretAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

