//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremoteSetVolumeLevel")
inline fun remoteSetVolumeLevel(block: remote.RemoteSetVolumeLevelKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteSetVolumeLevel =
  remote.RemoteSetVolumeLevelKt.Dsl._create(remote.Remotemessage.RemoteSetVolumeLevel.newBuilder()).apply { block() }._build()
object RemoteSetVolumeLevelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemoteSetVolumeLevel.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemoteSetVolumeLevel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemoteSetVolumeLevel = _builder.build()

    /**
     * <code>uint32 unknown1 = 1;</code>
     */
    var unknown1: kotlin.Int
      @JvmName("getUnknown1")
      get() = _builder.getUnknown1()
      @JvmName("setUnknown1")
      set(value) {
        _builder.setUnknown1(value)
      }
    /**
     * <code>uint32 unknown1 = 1;</code>
     */
    fun clearUnknown1() {
      _builder.clearUnknown1()
    }

    /**
     * <code>uint32 unknown2 = 2;</code>
     */
    var unknown2: kotlin.Int
      @JvmName("getUnknown2")
      get() = _builder.getUnknown2()
      @JvmName("setUnknown2")
      set(value) {
        _builder.setUnknown2(value)
      }
    /**
     * <code>uint32 unknown2 = 2;</code>
     */
    fun clearUnknown2() {
      _builder.clearUnknown2()
    }

    /**
     * <code>string player_model = 3;</code>
     */
    var playerModel: kotlin.String
      @JvmName("getPlayerModel")
      get() = _builder.getPlayerModel()
      @JvmName("setPlayerModel")
      set(value) {
        _builder.setPlayerModel(value)
      }
    /**
     * <code>string player_model = 3;</code>
     */
    fun clearPlayerModel() {
      _builder.clearPlayerModel()
    }

    /**
     * <code>uint32 unknown4 = 4;</code>
     */
    var unknown4: kotlin.Int
      @JvmName("getUnknown4")
      get() = _builder.getUnknown4()
      @JvmName("setUnknown4")
      set(value) {
        _builder.setUnknown4(value)
      }
    /**
     * <code>uint32 unknown4 = 4;</code>
     */
    fun clearUnknown4() {
      _builder.clearUnknown4()
    }

    /**
     * <code>uint32 unknown5 = 5;</code>
     */
    var unknown5: kotlin.Int
      @JvmName("getUnknown5")
      get() = _builder.getUnknown5()
      @JvmName("setUnknown5")
      set(value) {
        _builder.setUnknown5(value)
      }
    /**
     * <code>uint32 unknown5 = 5;</code>
     */
    fun clearUnknown5() {
      _builder.clearUnknown5()
    }

    /**
     * <code>uint32 volume_max = 6;</code>
     */
    var volumeMax: kotlin.Int
      @JvmName("getVolumeMax")
      get() = _builder.getVolumeMax()
      @JvmName("setVolumeMax")
      set(value) {
        _builder.setVolumeMax(value)
      }
    /**
     * <code>uint32 volume_max = 6;</code>
     */
    fun clearVolumeMax() {
      _builder.clearVolumeMax()
    }

    /**
     * <code>uint32 volume_level = 7;</code>
     */
    var volumeLevel: kotlin.Int
      @JvmName("getVolumeLevel")
      get() = _builder.getVolumeLevel()
      @JvmName("setVolumeLevel")
      set(value) {
        _builder.setVolumeLevel(value)
      }
    /**
     * <code>uint32 volume_level = 7;</code>
     */
    fun clearVolumeLevel() {
      _builder.clearVolumeLevel()
    }

    /**
     * <code>bool volume_muted = 8;</code>
     */
    var volumeMuted: kotlin.Boolean
      @JvmName("getVolumeMuted")
      get() = _builder.getVolumeMuted()
      @JvmName("setVolumeMuted")
      set(value) {
        _builder.setVolumeMuted(value)
      }
    /**
     * <code>bool volume_muted = 8;</code>
     */
    fun clearVolumeMuted() {
      _builder.clearVolumeMuted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemoteSetVolumeLevel.copy(block: remote.RemoteSetVolumeLevelKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteSetVolumeLevel =
  remote.RemoteSetVolumeLevelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

