//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremoteAppLinkLaunchRequest")
inline fun remoteAppLinkLaunchRequest(block: remote.RemoteAppLinkLaunchRequestKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteAppLinkLaunchRequest =
  remote.RemoteAppLinkLaunchRequestKt.Dsl._create(remote.Remotemessage.RemoteAppLinkLaunchRequest.newBuilder()).apply { block() }._build()
object RemoteAppLinkLaunchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemoteAppLinkLaunchRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemoteAppLinkLaunchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemoteAppLinkLaunchRequest = _builder.build()

    /**
     * <code>string app_link = 1;</code>
     */
    var appLink: kotlin.String
      @JvmName("getAppLink")
      get() = _builder.getAppLink()
      @JvmName("setAppLink")
      set(value) {
        _builder.setAppLink(value)
      }
    /**
     * <code>string app_link = 1;</code>
     */
    fun clearAppLink() {
      _builder.clearAppLink()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemoteAppLinkLaunchRequest.copy(block: remote.RemoteAppLinkLaunchRequestKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteAppLinkLaunchRequest =
  remote.RemoteAppLinkLaunchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

