//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremoteResetPreferredAudioDevice")
inline fun remoteResetPreferredAudioDevice(block: remote.RemoteResetPreferredAudioDeviceKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteResetPreferredAudioDevice =
  remote.RemoteResetPreferredAudioDeviceKt.Dsl._create(remote.Remotemessage.RemoteResetPreferredAudioDevice.newBuilder()).apply { block() }._build()
object RemoteResetPreferredAudioDeviceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemoteResetPreferredAudioDevice.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemoteResetPreferredAudioDevice.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemoteResetPreferredAudioDevice = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemoteResetPreferredAudioDevice.copy(block: remote.RemoteResetPreferredAudioDeviceKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteResetPreferredAudioDevice =
  remote.RemoteResetPreferredAudioDeviceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

