//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremoteTextFieldStatus")
inline fun remoteTextFieldStatus(block: remote.RemoteTextFieldStatusKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteTextFieldStatus =
  remote.RemoteTextFieldStatusKt.Dsl._create(remote.Remotemessage.RemoteTextFieldStatus.newBuilder()).apply { block() }._build()
object RemoteTextFieldStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemoteTextFieldStatus.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemoteTextFieldStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemoteTextFieldStatus = _builder.build()

    /**
     * <code>int32 counter_field = 1;</code>
     */
    var counterField: kotlin.Int
      @JvmName("getCounterField")
      get() = _builder.getCounterField()
      @JvmName("setCounterField")
      set(value) {
        _builder.setCounterField(value)
      }
    /**
     * <code>int32 counter_field = 1;</code>
     */
    fun clearCounterField() {
      _builder.clearCounterField()
    }

    /**
     * <code>string value = 2;</code>
     */
    var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>string value = 2;</code>
     */
    fun clearValue() {
      _builder.clearValue()
    }

    /**
     * <code>int32 start = 3;</code>
     */
    var start: kotlin.Int
      @JvmName("getStart")
      get() = _builder.getStart()
      @JvmName("setStart")
      set(value) {
        _builder.setStart(value)
      }
    /**
     * <code>int32 start = 3;</code>
     */
    fun clearStart() {
      _builder.clearStart()
    }

    /**
     * <code>int32 end = 4;</code>
     */
    var end: kotlin.Int
      @JvmName("getEnd")
      get() = _builder.getEnd()
      @JvmName("setEnd")
      set(value) {
        _builder.setEnd(value)
      }
    /**
     * <code>int32 end = 4;</code>
     */
    fun clearEnd() {
      _builder.clearEnd()
    }

    /**
     * <code>int32 int5 = 5;</code>
     */
    var int5: kotlin.Int
      @JvmName("getInt5")
      get() = _builder.getInt5()
      @JvmName("setInt5")
      set(value) {
        _builder.setInt5(value)
      }
    /**
     * <code>int32 int5 = 5;</code>
     */
    fun clearInt5() {
      _builder.clearInt5()
    }

    /**
     * <code>string label = 6;</code>
     */
    var label: kotlin.String
      @JvmName("getLabel")
      get() = _builder.getLabel()
      @JvmName("setLabel")
      set(value) {
        _builder.setLabel(value)
      }
    /**
     * <code>string label = 6;</code>
     */
    fun clearLabel() {
      _builder.clearLabel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemoteTextFieldStatus.copy(block: remote.RemoteTextFieldStatusKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteTextFieldStatus =
  remote.RemoteTextFieldStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

