//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremotePingResponse")
inline fun remotePingResponse(block: remote.RemotePingResponseKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemotePingResponse =
  remote.RemotePingResponseKt.Dsl._create(remote.Remotemessage.RemotePingResponse.newBuilder()).apply { block() }._build()
object RemotePingResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemotePingResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemotePingResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemotePingResponse = _builder.build()

    /**
     * <code>int32 val1 = 1;</code>
     */
    var val1: kotlin.Int
      @JvmName("getVal1")
      get() = _builder.getVal1()
      @JvmName("setVal1")
      set(value) {
        _builder.setVal1(value)
      }
    /**
     * <code>int32 val1 = 1;</code>
     */
    fun clearVal1() {
      _builder.clearVal1()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemotePingResponse.copy(block: remote.RemotePingResponseKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemotePingResponse =
  remote.RemotePingResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

