//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremoteAdjustVolumeLevel")
inline fun remoteAdjustVolumeLevel(block: remote.RemoteAdjustVolumeLevelKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteAdjustVolumeLevel =
  remote.RemoteAdjustVolumeLevelKt.Dsl._create(remote.Remotemessage.RemoteAdjustVolumeLevel.newBuilder()).apply { block() }._build()
object RemoteAdjustVolumeLevelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemoteAdjustVolumeLevel.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemoteAdjustVolumeLevel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemoteAdjustVolumeLevel = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemoteAdjustVolumeLevel.copy(block: remote.RemoteAdjustVolumeLevelKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemoteAdjustVolumeLevel =
  remote.RemoteAdjustVolumeLevelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

