//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: remotemessage.proto

package remote;

@kotlin.jvm.JvmName("-initializeremotePingRequest")
inline fun remotePingRequest(block: remote.RemotePingRequestKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemotePingRequest =
  remote.RemotePingRequestKt.Dsl._create(remote.Remotemessage.RemotePingRequest.newBuilder()).apply { block() }._build()
object RemotePingRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: remote.Remotemessage.RemotePingRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: remote.Remotemessage.RemotePingRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): remote.Remotemessage.RemotePingRequest = _builder.build()

    /**
     * <code>int32 val1 = 1;</code>
     */
    var val1: kotlin.Int
      @JvmName("getVal1")
      get() = _builder.getVal1()
      @JvmName("setVal1")
      set(value) {
        _builder.setVal1(value)
      }
    /**
     * <code>int32 val1 = 1;</code>
     */
    fun clearVal1() {
      _builder.clearVal1()
    }

    /**
     * <code>int32 val2 = 2;</code>
     */
    var val2: kotlin.Int
      @JvmName("getVal2")
      get() = _builder.getVal2()
      @JvmName("setVal2")
      set(value) {
        _builder.setVal2(value)
      }
    /**
     * <code>int32 val2 = 2;</code>
     */
    fun clearVal2() {
      _builder.clearVal2()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun remote.Remotemessage.RemotePingRequest.copy(block: remote.RemotePingRequestKt.Dsl.() -> kotlin.Unit): remote.Remotemessage.RemotePingRequest =
  remote.RemotePingRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

